import crypto from 'crypto';

import ActionAgent from '../services/agents/actionAgent.js';
import EmailAgent from '../services/agents/emailAgent.js';
import CalendarAgent from '../services/agents/calendarAgent.js';

// In-memory store
let pendingActions = [];

/**
 * Store actions generated by ActionAgent
 */
export const storePendingActions = async (input) => {
  const actions = await ActionAgent(input);

  actions.forEach((action) => {
    action.id = crypto.randomUUID();
    pendingActions.push(action);
  });

  return actions;
};

/**
 * Get pending actions
 */
export const getPendingActions = (req, res) => {
  res.json(pendingActions);
};

/**
 * Execute approved action
 */
export const executeAction = async (req, res) => {
  const action = req.body;

  try {
    // 🔑 tokens MUST come from logged-in user
    const tokens = req.user.googleTokens;

    if (!tokens) {
      return res.status(401).json({ error: 'Google tokens missing' });
    }

    if (action.type === 'send_email') {
      const emailAgent = new EmailAgent(tokens);

      await emailAgent.sendEmail(
        action.data.to,
        action.data.subject,
        action.data.body
      );
    } 
    else if (action.type === 'schedule_calendar_event') {
      const calendarAgent = new CalendarAgent(tokens);

      await calendarAgent.createEvent(
        action.data.summary,
        action.data.start,
        action.data.end
      );
    }

    // Remove executed action
    pendingActions = pendingActions.filter(a => a.id !== action.id);

    res.json({ success: true });
  } catch (error) {
    console.error('Failed to execute action:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
};
